project_id = "fuvwfwkipsfnvpjefemt"

[functions.create-test-accounts]
verify_jwt = false

[functions.atlaas-ai-chat]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.send-receipt-email]
verify_jwt = false

[functions.ocr-menu]
verify_jwt = false

[functions.wallet-topup-checkout]
verify_jwt = false

[functions.prime-checkout]
verify_jwt = false

[functions.verify-wallet-topup]
verify_jwt = false

[functions.send-twilio-message]
verify_jwt = false

[functions.send-otp-sms]
verify_jwt = false

[functions.send-order-sms]
verify_jwt = false
